---

- name: Symfony2 | Dependencies | Composer | Check if composer needs to be downloaded
  stat: 
    path: "{{ symfony2_root }}/composer.phar"
  when: "symfony2_composer_path is not defined or '' == symfony2_composer_path"
  register: composer_file
  ignore_errors: true

- name: Symfony2 | Dependencies | Composer | Download composer
  get_url: 
    url: "https://getcomposer.org/composer.phar"
    dest: "{{ symfony2_root }}/composer.phar"
    mode: 0755
    validate_certs: no
  when: composer_file|success and not composer_file|skipped and not composer_file.stat.exists
  ignore_errors: true
  register: composer_installed

- name: Symfony2 | Dependencies | Composer | Set symfony2_composer_path
  set_fact:
    symfony2_composer_path: "{{ symfony2_root }}/composer.phar"
  when: composer_installed|success and (symfony2_composer_path is not defined or '' == symfony2_composer_path)
  ignore_errors: true

- name: Symfony2 | Dependencies | Composer | Run composer install
  shell: >
    cd {{ symfony2_current_release }} && SYMFONY_ENV={{ symfony2_environment }} {{ symfony2_php_cmd }} {{ symfony2_composer_path }} install {{ symfony2_composer_options }}
  when: composer_installed|success or symfony2_composer_path
  register: composer_install
  ignore_errors: true

- include: failed.yml
  when: composer_install|failed
