---

- name: Symfony2 | Deploy | SVN | Get sources from the repository
  subversion:
    repo: "{{ symfony2_repo }}"
    dest: "{{ symfony2_current_release }}"
    revision: "{{ symfony2_svn_revision }}"
  ignore_errors: true
  register: symfony2_svn_deploy
