---

- name: Symfony2 | Prepare | Get current date
  shell: date +{{ symfony2_release_format }}
  register: release_date
  when: symfony2_release is not defined

- name: Symfony2 | Prepare | Set release version
  set_fact:
     symfony2_release: "{{ release_date.stdout }}"
  when: symfony2_release is not defined

- name: Symfony2 | Prepare | Set symfony2_current_release
  set_fact:
    symfony2_current_release: "{{ symfony2_release_root }}/{{ symfony2_release }}"
  when: symfony2_current_release is not defined

- name: Symfony2 | Prepare | Create release directory
  file:
    state: directory
    path: "{{ symfony2_current_release }}"
